import type {Event, Note, Task} from './types';
export const localDate=(date=new Date())=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`};
const today=localDate();
export const seedTasks:Task[]=[{id:'1',title:'Pripraviť týždenný plán',due:today,priority:'Vysoká',done:false},{id:'2',title:'Prečítať kapitolu z knihy',due:today,priority:'Stredná',done:false},{id:'3',title:'Večerná prechádzka',due:localDate(new Date(Date.now()+86400000)),priority:'Nízka',done:true}];
export const seedNotes:Note[]=[{id:'1',title:'Vitaj v Planore',body:'Toto je tvoje pokojné miesto pre myšlienky, úlohy a plány.',tags:['štart'],pinned:true,updated:today},{id:'2',title:'Nápady na víkend',body:'Výlet do prírody, dobrá káva a trochu času bez obrazoviek.',tags:['osobné'],pinned:false,updated:today}];
const seedStart=new Date();seedStart.setHours(10,0,0,0);const seedEnd=new Date(seedStart);seedEnd.setHours(11,0,0,0);
export const seedEvents:Event[]=[{id:'event-1',title:'Týždenné plánovanie',description:'Pokojný čas na nastavenie priorít.',startAt:seedStart.toISOString(),endAt:seedEnd.toISOString(),allDay:false,createdAt:seedStart.toISOString(),updatedAt:seedStart.toISOString()}];
const VERSION=1,LIMIT=500,KEYS={tasks:'planora_tasks',notes:'planora_notes',events:'planora_events'} as const;const protectedFallbacks=new WeakSet<object>();type Kind=keyof typeof KEYS;
export type LoadStatus='ok'|'empty'|'legacy'|'corrupt'|'invalid'|'unavailable';export type LoadResult<T>={data:T;status:LoadStatus};export type SaveResult={ok:true}|{ok:false;error:unknown};type Envelope<T>={version:number;data:T};
const text=(v:unknown,max:number):v is string=>typeof v==='string'&&v.length<=max;
const validTask=(v:unknown):v is Task=>{if(!v||typeof v!=='object')return false;const t=v as Task;return text(t.id,100)&&text(t.title,500)&&text(t.due,30)&&['Nízka','Stredná','Vysoká'].includes(t.priority)&&typeof t.done==='boolean'};
const validNote=(v:unknown):v is Note=>{if(!v||typeof v!=='object')return false;const n=v as Note;return text(n.id,100)&&text(n.title,500)&&text(n.body,10000)&&Array.isArray(n.tags)&&n.tags.length<=30&&n.tags.every(t=>text(t,100))&&typeof n.pinned==='boolean'&&text(n.updated,40)};
export const eventIsValid=(startAt:string,endAt:string,allDay=false)=>allDay||new Date(endAt).getTime()>new Date(startAt).getTime();
const validEvent=(v:unknown):v is Event=>{if(!v||typeof v!=='object')return false;const e=v as Event;return text(e.id,100)&&text(e.title,500)&&text(e.description,10000)&&text(e.startAt,40)&&text(e.endAt,40)&&typeof e.allDay==='boolean'&&text(e.createdAt,40)&&text(e.updatedAt,40)&&eventIsValid(e.startAt,e.endAt,e.allDay)};
const validList=<T,>(v:unknown,check:(v:unknown)=>v is T):v is T[]=>Array.isArray(v)&&v.length<=LIMIT&&v.every(check);const checks={tasks:validTask,notes:validNote,events:validEvent};
function save<T>(kind:Kind,data:T[]):SaveResult{try{if(protectedFallbacks.has(data as object))return{ok:false,error:new Error('Protected fallback')};if(!validList(data,checks[kind] as (v:unknown)=>v is T))return{ok:false,error:new Error('Invalid storage data')};localStorage.setItem(KEYS[kind],JSON.stringify({version:VERSION,data}));return{ok:true}}catch(error){return{ok:false,error}}}
function load<T>(kind:Kind,fallback:T[]):LoadResult<T[]>{const check=checks[kind] as (v:unknown)=>v is T;let raw:string|null;try{raw=localStorage.getItem(KEYS[kind])}catch{protectedFallbacks.add(fallback);return{data:fallback,status:'unavailable'}}if(raw===null)return{data:fallback,status:'empty'};let parsed:unknown;try{parsed=JSON.parse(raw)}catch{protectedFallbacks.add(fallback);return{data:fallback,status:'corrupt'}}if(validList(parsed,check)){const result=save(kind,parsed);return{data:parsed,status:result.ok?'legacy':'unavailable'}}if(parsed&&typeof parsed==='object'&&'version'in parsed&&'data'in parsed){const e=parsed as Envelope<unknown>;if(e.version===VERSION&&validList(e.data,check))return{data:e.data,status:'ok'}}protectedFallbacks.add(fallback);return{data:fallback,status:'invalid'}}
export const loadTasksResult=()=>load('tasks',seedTasks);export const loadNotesResult=()=>load('notes',seedNotes);export const loadEventsResult=()=>load('events',seedEvents);export const loadTasks=()=>loadTasksResult().data;export const loadNotes=()=>loadNotesResult().data;export const loadEvents=()=>loadEventsResult().data;
export const saveTasksResult=(data:Task[])=>save('tasks',data);export const saveNotesResult=(data:Note[])=>save('notes',data);export const saveEventsResult=(data:Event[])=>save('events',data);const notify=(r:SaveResult)=>{if(!r.ok&&!(r.error instanceof Error&&r.error.message==='Protected fallback'))window.dispatchEvent(new Event('planora:storage-error'))};export const saveTasks=(d:Task[]):void=>notify(saveTasksResult(d));export const saveNotes=(d:Note[]):void=>notify(saveNotesResult(d));export const saveEvents=(d:Event[]):void=>notify(saveEventsResult(d));
export const upsertEvent=(events:Event[],event:Event)=>events.some(x=>x.id===event.id)?events.map(x=>x.id===event.id?event:x):[...events,event];
export const removeEvent=(events:Event[],id:string)=>events.filter(x=>x.id!==id);
export const allDayEventRange=(date:string)=>{const start=new Date(`${date}T00:00:00`),end=new Date(start);end.setDate(end.getDate()+1);return{startAt:start.toISOString(),endAt:end.toISOString()};};
